on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  cache-and-install:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          # TODO: This should instead be: node-version-file: .nvmrc, but this action doesn't support Node.js version 20 yet. Issue: https://github.com/pnpm/action-setup/issues/99
          node-version: 18

      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false

      - name: Get pnpm store directory
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path --silent)" >> $GITHUB_ENV
      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ env.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-
      - name: Install dependencies
        run: pnpm install

      # TODO: This should only run on changed files.
      - name: Run formatter
        run: pnpm run prettier

      # TODO: This should only run on changed files.
      - name: Run linter
        run: pnpm run lint
